### PR TITLE
Intergration tests

### PR DESCRIPTION
**Pull request by Beardless-sheik**
In this pull request, Integration tests were added for the following pages: 
- Login Page
- User Index & Show Page
- Post Index & Show Page

Tests followed specific user stories outlined in the project brief and implemented as descriptions in the test suite

### CODE REVIEW

**Review by KDlamini — CHANGES_REQUESTED** [review]
### Hi team @Beardless-sheik, @Abenezer-Tilahun 🙋‍♀️,  

Great work so far! 💯 
There are some issues that you still need to work on improving your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 
✔️  Has featured tests for all views
✔️  Correct PR title and description
✔️  Correct use of Gitflow 
✔️  Commit messages are meaningful
✔️  No linter errors

## Required Changes ♻️
 
 - [ ] Kindly look into your tests and make sure that they all pass. Currently, most of the tests do not pass.
 
image

-  If this is a mistake on my end kindly attach a screenshot of your passing tests.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
N/A

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Beardless-sheik** [comment]
Hi @KDlamini . Yes the tests pass on our end. Could be an error on your DB creation. Kindly see attached screenshot

image

image

**Comment by KDlamini** [comment]
Hi @Beardless-sheik

Okay, Great job!!! 
Kindly request another review 👍🏾

**Comment by KDlamini** [comment]
Hi @Beardless-sheik

Okay, Great job!!! 
Kindly request another review :thumbs_up

**Review by mikethreels — APPROVED** [review]
Hi Alick, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
